import 'package:diesel/diesel.dart';

import 'schema.dart';

part 'models.g.dart';

/// Data classes over the generated [schema.dart]. The row readers
/// (`userMapper` / `postMapper`) are generated by `diesel_codegen` from the
/// `@Queryable` annotations — run `dart run build_runner build`.
///
/// Note: `active` is `int` because SQLite has no native boolean.
@Queryable(Users)
class User {
  final int id;
  final String name;
  final int age;
  final int active;
  const User(this.id, this.name, this.age, this.active);

  @override
  String toString() => 'User(#$id $name, age $age)';
}

@Queryable(Posts)
class Post {
  final int id;
  final String title;
  final int views;

  /// A relation, not a column — excluded from generation, filled by the join.
  @ignore
  final User? author;

  const Post(this.id, this.title, this.views, {this.author});

  Post withAuthor(User author) => Post(id, title, views, author: author);

  @override
  String toString() => 'Post("$title", $views views, by ${author?.name})';
}
