/// Data classes over the generated [schema.dart], split across files to show
/// that `@Queryable` / `@Relation` work across library boundaries.
///
/// Everything below the constructors is generated by `diesel_codegen` from the
/// `@Queryable` / `@Relation` annotations — run `dart run build_runner build`.
/// For each annotated class the generator emits (into a self-contained
/// `<file>.g.dart`):
///   * a composable, alias-parameterized row reader `_$XFromRow`,
///   * a reusable `xMapper` (a `RowMapper<X>`),
///   * and, when the class has `@Relation`s, a self-mapping join query getter
///     (e.g. `postQuery`) that wires up the joins, aliases and the
///     nested decoding for you.
library;

export 'post.dart';
export 'user.dart';
