// GENERATED by `diesel_dart print-schema`. Do not edit by hand.
import 'package:diesel/diesel.dart';

abstract final class Posts {
  static const id = PrimaryKey<int, Posts>('posts', 'id', SqlType.integer);
  static const authorId = Ref<int, Posts, Users>('posts', 'author_id', SqlType.integer, references: Users.id);
  static const title = ValueColumn<String, Posts>('posts', 'title', SqlType.text);
  static const views = ValueColumn<int, Posts>('posts', 'views', SqlType.integer);
  static const table = TableRef<Posts>('posts', [id, authorId, title, views]);
}

abstract final class Users {
  static const id = PrimaryKey<int, Users>('users', 'id', SqlType.integer);
  static const name = ValueColumn<String, Users>('users', 'name', SqlType.text);
  static const age = ValueColumn<int, Users>('users', 'age', SqlType.integer);
  static const active = ValueColumn<int, Users>('users', 'active', SqlType.integer);
  static const managerId = Ref<int?, Users, Users>('users', 'manager_id', SqlType.integerOrNull, references: Users.id);
  static const table = TableRef<Users>('users', [id, name, age, active, managerId]);
}

